SaturnFramework/Saturn

src/Saturn/ControllerHelpers.fs
Part 1 of 2 to address #31
happy for any feedback
=> Add new renderXml to render XmlNode based templates

paket.dependencies, paket.lock, src/Saturn/Application.fs, src/Saturn/Pipelines.fs, src/Saturn/paket.references
=> Authorization helper

src/Saturn/Application.fs
=> expose IWebHostBuilder from application CE

src/Saturn/Pipelines.fs
=> Fix `set_body` overload

src/Saturn/CORS.fs, src/Saturn/Common.fs, src/Saturn/Controller.fs, src/Saturn/ControllerHelpers.fs, src/Saturn/Links.fs, src/Saturn/Router.fs
Should handle #55.
I also cleaned up the `halt` method as part of this because the response wrappers were using basically it all over.
=> Add most of the missing XML docs

src/Saturn/Application.fs
Adds the `cli_arguments` operation to the Application CE.
These flow into `CreateDefaultBuilder(args)` and enable default functionality like `--urls` and the CommandLine configuration source.
Another road to take could have been to let `application` return `string array -> IWebHostBuilder` and pass the args into it through run. However as that's a breaking change I thought to keep it like this.
=> Add cli_arguments operation to the Application CE 

src/Saturn/Links.fs
Would be something like this then right @rmunn ?
=> Fix issue 71

src/Saturn/Pipelines.fs
=> Await before adding result to Items.["RequestModel"] fixes #70

src/Saturn/Application.fs
=> Fix GitHub OAuth

paket.dependencies, src/Saturn/Application.fs, src/Saturn/paket.references
=> Add Google OAuth

src/Saturn/Application.fs
Add custom operations to `application` CE that will allow to override settings of serializers or serializers themselves.
=> Add operations for customizing serialization

src/Saturn/Controller.fs
New 'except' function taking actions to remove from the complete set of actions, closes #91
=> Action subtraction via controller except function

src/Saturn/Controller.fs
=> Handle possible "except [All]" silliness

src/Saturn/Application.fs
=> Support custom MIME types

src/Saturn.Extensions.Turbolinks/Turbolinks.fs
=> Fix turbolinks header application 

src/Saturn/Controller.fs, tests/Saturn.UnitTests/ControllerTests.fs
Fix for #109. See the last commit for the fix. I've included a test that demonstrates what should happen after the changes. This may not be the solution we want, but I think it helps demonstrate the issue.
=> WIP: Fix for plugs firing twice

src/Saturn/Application.fs
=> Change `use_config` to accept `IConfiguration -> 'a`

src/Saturn/Common.fs, src/Saturn/Controller.fs, src/Saturn/Router.fs, tests/Saturn.UnitTests/RouterTests.fs, tests/Saturn.UnitTests/Saturn.UnitTests.fsproj
Fix https://github.com/SaturnFramework/Saturn/issues/145
Adds `case_insensitive` operation to `router` and `controller` that toggles case insensitive routing for this particular component.
=> Case insensitive support

sample/Controller.Sample/Controller.Sample.fs, src/Saturn/Controller.fs, tests/Saturn.UnitTests/ControllerTests.fs, tests/Saturn.UnitTests/Helpers.fs
The new version of https://github.com/SaturnFramework/Saturn/pull/132 using the overload trick described by @panesofglass in https://github.com/panesofglass/computation-expressions-workshop/blob/master/exercises/08_EDSLs.md#overloading and https://wizardsofsmart.wordpress.com/2019/01/01/yet-another-f-web-framework/
=> Automatic dependency injection for controller. V2

sample/Saturn.Sample/Saturn.Sample.fs, src/Saturn/Diagnostics.fs
=> Add routing diagnostic page

src/Saturn/CORS.fs
=> Don't use setBody on CORS 204

.paket/Paket.Restore.targets, paket.lock
Giraffe 4.0.0 had a bug, not sure what it was, that caused at least the ChannelSample to fail. updating to 4.0.1 fixes the sample.
Fixes: https://github.com/SaturnFramework/Saturn/issues/208
=> Update giraffe to 4.0.1

src/Saturn/Router.fs
=> Fix really minor typo:

src/Saturn/Controller.fs, tests/Saturn.UnitTests/ControllerTests.fs
=> Fix edit action in controller

src/Saturn.Extensions.Authorization/OAuth.fs, src/Saturn.Extensions.Authorization/paket.references, src/Saturn.Extensions.OpenIdConnect/OpenId.fs, src/Saturn.Extensions.OpenIdConnect/Saturn.Extensions.OpenIdConnect.fsproj
=> Moves OIDC to Extensions.Authorization

sample/ChannelsSample/ChannelsSample.fs, src/Saturn/Channels.fs, tests/Saturn.UnitTests/Helpers.fs
* Adds type-safety to the `Message` in `handle` action
* Renames SocketInfo to ClientInfo
* Adds the whole bunch of documentation
* Mark `SocketHub` and `SocketMiddleware` classes as internal
=> Channel improvements

sample/ChannelsSample/.config/dotnet-tools.json, sample/ChannelsSample/ChannelsSample.fs, sample/ChannelsSample/index.html
closes #248.
This pull request will add a sample static html page that calls into the channel topics to serve as a more fleshed out sample
=> Add sample consumer in channels sample

src/Saturn/Application.fs
Fix typo getConfiguration - #266
=> Fix typo getConfiguration

src/Saturn/Application.fs, src/Saturn/Channels.fs, src/Saturn/Controller.fs, src/Saturn/ControllerEndpoint.fs, src/Saturn/Pipelines.fs, src/Saturn/Router.fs, src/Saturn/RouterEndpoint.fs, tests/Saturn.UnitTests/ControllerTests.fs, tests/Saturn.UnitTests/EndpointControllerTests.fs
This builds on #276 to provide bit better (IMHO) API surface for DI operations.
=> Rework DI system

src/Saturn/Controller.fs
This should preserve the stack trace when exceptions are thrown while using controllers that have no dedicated error handler.
This solves a part of #280
=> Preserve stack trace by default in controller (#280)

src/Saturn/Channels.fs
Should fix #288 
This is very urgent for our project. Is there a timeframe for the next release?
=> Fixes exception propagation when using channels

src/Saturn/Channels.fs
This is a common thing to happen and is unavoidable, so this should not be logged as an error IMO.
=> Log prematurely closed WebSocket connections as info, not as error

.github/workflows/benchmark.yml, .github/workflows/build.yml, .github/workflows/docs.yml, .github/workflows/publish.yml, .gitpod.yml
=> Update gitpod and actions infra

tests/Saturn.UnitTests/ControllerTests.fs
With this PR, I'm sending a cosmetic update, only fixing the `updateAction` function indentation. Previously it was ahead of the other functions.
Let me know if you'd like me to change something before merging this PR.
=> [Cosmetic] Update indentation

tests/Saturn.UnitTests/RouterTests.fs
With this PR I'm adding more test scenarios for the router feature. The endpoint that was added to cover the following HTTP verbs:
* DELETEF
Let me know if you guys have any suggestions.
=> Added unit test for deletef request

sample/EndpointRoutingSample/Program.fs
Minor spelling error fix in code comments
Issue listed here #371
=> Spell check sample application
