- README.md
no longer required to do a `chmos +x build.sh` because the template was fixed.
> remove unneeded readme step

- src/Saturn/Saturn.fsproj
I was wondering why I couldn't see any documentation in the tooltips until I realized the `GenerateDocumentationFile` property was missing in the .fsproj :)
> Generate documentation XML file

- sample/Saturn.Sample/Saturn.Sample.fs
- src/Saturn/Router.fs
Delete routes are currently not routed. Just an extremely small bug where put routes were generated twice.
> Delete requests are not routed

- sample/Controller.Sample/Controller.Sample.fs
- src/Saturn/Application.fs
- src/Saturn/Controller.fs
- src/Saturn/Diagnostics.fs
- src/Saturn/Router.fs
- src/Saturn/Saturn.fsproj
This PR is adding ability to generate on application startup file containing information about routing of the application. This enables creating really interesting set of developer tools such as command line and GUI clients (like the ones shown by MSFT for ASP.NET during Build), Swagger generator, automatic testing tools etc.
Known limitations:
* It supports only routing defined by `scope` and `controller` CE - i have no way to introspect webparts created by lower level Giraffe combinators that can also include routing.
* The code is super hacky, however it should be executed (mostly) at application startup. I probably should investigate disabling mechanism that collects routing data after server has started.
> Add basic diagnostics files

- src/Saturn/Application.fs
- src/Saturn/Controller.fs
- src/Saturn/Router.fs
I have also changed the other places where `foldBack (>=>) ` was also used, those were applied in incorrect order too.
> Fixes #72 by composing from acc to element instead of element to acc

- sample/Controller.Sample/Controller.Sample.fs
- src/Saturn/Controller.fs
- src/Saturn/ControllerHelpers.fs
- src/Saturn/Saturn.fsproj
This extends controller CE to support generic output type from the controller actions. If action returns `Task<HttpContext option>`  nothing changes - it's non breaking change for existing code.
If action will return something else (`Task<'a>`) then we pipe `'a` through new `Controller.response` helper.
`Controller.response` helper is transforming any object to correct response that client expects. It checks `Accept` header (and if that's not available it checks `Content-Type` header) to find correct supported serialization format. 
We also support automatically returning `Giraffe.GiraffeViewEngine.XmlNode` which is Giraffe's server side view type.
> Typed controller output

- src/Saturn.Extensions.Authorization/OAuth.fs
CookiesAlreadyAdded is not actually set because
"if not flag then 
flag <- true " gets executed too late, after use_auth, inside "run app" call, so that "let mutable flag = state.CookiesAlreadyAdded" is always false and System.InvalidOperationException: Scheme already exists: Cookies still occurs
> fix adding multiple auth sources

- src/Saturn/Controller.fs
Fixes https://github.com/SaturnFramework/Saturn/issues/108 by passing the normal handler to the "/" path
> Fixes #108 

- src/Saturn/Controller.fs
Rebased on top of pr of @TWith2Sugars.
Includes extra changes around string conversions of 'Key and a safety check for sub controller routes that don't start with a forward slash. 
These changes have been tested on nested controllers and on mixed key controllers.
> Fix 115 subcontroller behavior

- src/Saturn/ControllerHelpers.fs
- tests/Saturn.UnitTests/ControllerTests.fs
*adds tests to verify that implicit return of xmlnode as well as explit result from renderHtml get doctype element prepended
*adds test to verify that doctype is not prependend in case where the user returns a fully parsed html document as string
*changes direct calls of context writer methods to helper methods (to keep interface uniform)
> fixes missing doctype in html controller actions

- sample/Saturn.Sample/Saturn.Sample.fs
This is a tiny one, but I'm looking for a spot to get my feet wet by making a small contribution. If this isn't helpful, feel free to disregard, or even better point me in a direction where I could be more helpful.
Thanks
It would be helpful if the sample set the 404 status code when using the not_found_handler. 
I used the sample as a starting point for my project and incorrectly assumed that the status code would be set automatically.
> Suggestion - set 404 status code on not found handlers in sample

- src/Saturn/Controller.fs
- tests/Saturn.UnitTests/ControllerTests.fs
Adds test to verify behavior for DeleteAll changes.
Also fixes bug where plug was not fired when plug [All] was added to controller CE with delete_all action provided.
> Updates Index and DeleteAll so that plugs won't fire twice w/ BONUS bug fix.

- src/Saturn/Application.fs
- src/Saturn/Authentication.fs
- src/Saturn/Router.fs
- src/Saturn/Saturn.fsproj
This is proof of concept for the suggestions discussed in https://github.com/SaturnFramework/Saturn/issues/96. CC: @rmunn
* Marks `use_custom_oauth` as obsolete
* Adds `use_oauth_with_config` instead. It's following naming conventions from other authentication methods (`use_cookies_authentication_with_config` and `use_jwt_authentication_with_config`).
* Adds `use_oauth` that takes simple record representing the usual OAuth settings and claims.
> OAuth refactoring

- src/Saturn/Controller.fs
- tests/Saturn.UnitTests/ControllerTests.fs
Controller 'Key should always match up to a single path segment
See https://github.com/SaturnFramework/Saturn/issues/160#issuecomment-465747648 for bug, see code comments and tests for more explanation. 
I believe this is the right thing to do given the other 'Key type's routing behavior.
> Controller key should always match up to a single path segment

- sample/ChannelsSample/Program.fs
- src/Saturn/Application.fs
It seems like you can't call `Configure` multiple times, because in my local testing of the channels feature I could never get a channel to negotiate!
This MR changes the registration order around a bit so that there's an explicit list of modifications that we build up with comments as to why they are layered in such a way.
With this, the channel sample works for me.
> fix channel registration ordering so that channels happen before giraffe

- src/Saturn/CSRF.fs
We should allow users to define their own csrf-recovery handlers, so I made `tryCsrf` and then implemented `csrf` in terms of that.
By default all of the same error-handling occurs, but I took the opportunity to make a type out of the errors so that users could figure out what they wanted to do.
> add a tryCsrf handler as well as the csrf handler

- src/Saturn.Extensions.Authorization/OAuth.fs
Should fix the error mentioned in #220
> Fixed naming collision in Auth extensions, #221

- sample/ChannelsSample/ChannelsSample.fs
- src/Saturn/Channels.fs
Breaking change. Could be done in a none breaking way, by adding new operators to allow code to opt-in to see the socketId, but adds considerable complexity.
Added a SocketInfo record to wrap the SocketId, to allow more information about the socket to be added at a later date without a breaking change.
> Allow all functions in a channel to see the socketId

- docs/content/tutorials/adding-pages.md
- docs/content/tutorials/adding-saturn-to-an-existing-giraffe-app.md
- docs/content/tutorials/how-to-start.md
closes https://github.com/SaturnFramework/Saturn/issues/243
> WIP: Documentation: add Hello World and How to add it to Giraffe

- src/Saturn/Application.fs
The default list of compressable MIME-types is quite small:
https://docs.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-3.1#mime-types
The types added in this PR are:
- SVG images that are XML-files. Those are common and large text files
- YAML-files. They are text-based resources, like dictionaries.
- Uncompressed truetype-fonts, they can be large and they will compress quite well.
- Default settings from Azure CDN compression enabled MIME-types.
> Added a few more mime-types that should be compressed.

- docs/content/explanations/routing.fsx
- docs/content/tutorials/adding-pages.md
- docs/content/tutorials/how-to-start.md
Some pages are linking to `.md` files that do not exist outside of the source repository, giving 404 errors.
> fix broken links in docs

- src/Saturn/Pipelines.fs
Looks like this header was incorrect as evidenced by the doc lines being the correct header. This should be `x-frame-options` according to [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options)
> Fix putSecureBrowserHeaders header typo

- src/Saturn/Application.fs
Add the additionalMime list to ResponseCompressionDefaults.MimeTypes.
(appearently the passed options do not contain the defaults)
> fix issue #270: application/json not compressed in response

- src/Saturn.Extensions.Turbolinks/Turbolinks.fs
This fixes #262. 
It's a somewhat breaking change, but like we discussed in the issue we can see this as a bug-fix.
I didn't see any docs/tests/samples that needed to be changed because of this, but let me know if there is anything that I should update.
> Include querystring in Turbolinks-location.

- docs/generators/partials/menu.fsx
Typo fix in left navigation of Saturn documentation.
Also fix typo in function name.
> typo fix: s/shortucts/shortcuts/

- paket.dependencies
- paket.lock
Should fix #309 by lowering the version pinned in paket.dependencies.
> lower fsharp.core dependency to 5.x so users can float

- sample/Saturn.Sample/Saturn.Sample.fs
In this pull request, I'm fixing some grammatical mistakes in the comments of the `Saturn.Sample.fs` file and changing the style of those comments to follow a specific rule.
With this change, the readability of the comments will be enhanced.
> Enhance the comments for the Saturn.Sample.fs file

- CONTRIBUTING.md
- README.md
I have noticed that the project lacks instructions about how to run the automated tests inside it. So I decided to contribute by providing a new section to the README.md where I teach people how to run those tests and how to run a specific test in cases where folks want to.
Also, I have fixed the CONTRIBUTING.md file where it shows a command to assert that all the tests are still passing. In this change, I just wrote basically the same thing I did for the README.md.
> Add test instructions to the README.md and fix the test instructions in the CONTRIBUTING.md

- tests/Saturn.UnitTests/SimpleTests.fs
With this PR I'm fixing a typo in the module name for the `SimpleTests.fs` file, along with other minor fixes in this file.
* Rename module: `SimpleTets` -> `SimpleTests`
* Remove empty line
* Change the `mkLinks` function to avoid receiving unused parameter
* Fix indentation for the router
> SimpleTests - Fix typo

- docs/content/tutorials/how-to-start.md
With this PR, I'm: 
* Updating the `how-to-start` guide due to the major .NET update of the project ([issue link](https://github.com/SaturnFramework/Saturn/issues/321)).
* Update the command used to start the sample application in watch mode. It was required to change due to the lack of [FAKE](https://github.com/fsprojects/FAKE) in the template.
---
This PR is related to this issue, where a user had difficulty to start using this tool:
* https://github.com/SaturnFramework/Saturn/issues/349
It is also linked to this other PR, where I sent some code to update the Saturn template and remove some broken configurations (they are broken in .NET 6, previously they were required):
* https://github.com/SaturnFramework/Saturn.Cli/pull/39
> Update `how-to-start` guide

- tests/Saturn.UnitTests/RouterTests.fs
With this PR I'm adding more test scenarios for the `router` feature. The endpoints added cover the following HTTP verbs:
* PUT
* DELETE
I'm also adding some GET endpoints to test the `getf` method.
Let me know if there is something you'd like to change before getting this PR merged.
> Add more test scenarios for the `router` feature

- .github/workflows/benchmark.yml
- .github/workflows/build.yml
- .github/workflows/docs.yml
- .github/workflows/publish.yml
With this PR I'm:
* Updating the version of both the `checkout` and `setup-dotnet` actions used.
* Pin the environment version to avoid problems popping up in the future due to some release (avoiding `latest` tags whenever possible).
* Add a workaround for the MacOS `dotnet tool restore`, which was failing.
Let me know if there is anything you'd like to change in this PR.
The MacOS workaround I found in this issue: https://github.com/actions/runner-images/issues/5768#issuecomment-1162684820. I added a new step to fix it when we're using MacOS as the host environment.
Other than this, one can find the actions mentioned before in the following links:
* checkout: https://github.com/actions/checkout
* setup-dotnet: https://github.com/actions/setup-dotnet
Finally, regarding the GitHub Actions …
> Update GitHub Actions

- src/Saturn/RouterEndpoint.fs
This small PR is intended to fix a typo in the `RouterEndpoint.fs` file, related to the RouterState.
* `Forawrds` -> `Forwards`
> Fix RouterEndpoint.fs typo

- CONTRIBUTING.md
- README.md
With this PR I'm basically replacing the references to the `master` branch in this repository by references to the `main` branch.
> Replace `master` branch references by `main` branch

- src/Saturn/Controller.fs
- src/Saturn/ControllerEndpoint.fs
Tiny code clean-up.
Fix for CA1865-1867: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1865-ca1867
> Use char-based override instead of string in EndsWith
